### PR TITLE
mu4e renaming internal functions from ~ to -- syntax

### PR DESCRIPTION
**Pull request by bramadams**
This pull request addresses the bulk of the big API changes in mu4e that happened from mu 1.10 on, for example: https://github.com/djcb/mu/commit/1799c69451e68767b11078a68df3c9de8bb2d6c4

Some API changes were not simple renamings, so some comments are left to indicate where further changes are required. Any suggestions welcome!

### CODE REVIEW

**Comment by lordpretzel** [comment]
Hi, thanks for the work. I am going through the comments to see what can be done and will test this (unfortunately my docker test setup for this project which allowed GUI testing against multiple mu versions is broken on Apple Silicon which is my main driver right now) so I probably will only test on mu 1.12 for now.

**Comment by lordpretzel** [comment]
I used this as an excuse to finally fix a long standing bug on 1.10 / 1.12 where inline images are not shown in the HTML view. At some point I should probably move all the version specific code into separate files or at least reorg the main file better. If you can test whether this fixes your problems that would be great.

**Comment by bramadams** [comment]
Hi, thanks for looking into this!

I seem to get an error with this last commit for one specific HTML email (the one who gave the issue solved by PR #33):
```emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  substring-no-properties(nil)
  #f(compiled-function (attachment) #<bytecode -0x1216157577077110>)(("bla_logo_bw.png" #<buffer  *mm*-512642> ("image/png" (name . "bla_logo_bw.png")) base64 nil ("inline" (filename . "bla_logo_bw.png")) nil nil "<8df18542fcc1268d15b4444f0d00455b@bla.app>"))
  mu4e-views-mu4e~write-body-and-headers-to-html([redacted])
```

**Comment by lordpretzel** [comment]
There was a bug in the inline image extraction function mu4e-views--extract-inline-images that did call itself on multipart message. I've pushed a fix

**Comment by bramadams** [comment]
Thanks, this fixes the issue with that email. I've been browsing my emails this morning, and all seems to work well!

**Pull request merged**
